datasource:
  default: ${APP_ENV}
  development:
    username: user
    password: user
    url: "jdbc:h2:./database"
  production:
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    url: "jdbc:postgresql:./database"

ebean:
  ddl:
    run: true
    generate: true
    seedSql: seed.sql
  migration:
    run: true